# .github/workflows/pytest.yml
name: PyTest
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: pip install -r requirements.txt
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test with pytest
        env:
          pytest_verbosity: 2
        run: pytest --github-report test
